# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_morsecombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morsecombination',
            name='combination',
            field=models.CharField(max_length=4),
        ),
    ]
